stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login
    - docker build -t imagegitlabci .
    - docker run -d --name container2 -p 3005:3005 imagegitlabci

   #- docker tag imagegitlabci kefitouka2830/imagegitlabci:latest
   #- docker push kefitouka2830/imagegitlabci:latest
   