stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
   
    #IMAGE_NAME: "recordweb"  
    #CONTAINER_NAME:  "recordweb"
  script:
   
   - docker build -t imagegitlabci .
   - docker run -d --name container21 -p 3005:3005 imagegitlabci
   #- docker tag imagegitlabci kefitouka2830/imagegitlabci:latest
   #- docker push kefitouka2830/imagegitlabci:latest
